--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "KITRI"."MEMBER" 
   (	"EMAIL" VARCHAR2(35 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(35 BYTE), 
	"AGE" NUMBER(3,0), 
	"GRADE" NUMBER(1,0), 
	"GENDER" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KITRI.MEMBER
SET DEFINE OFF;
Insert into KITRI.MEMBER (EMAIL,NAME,PASS,AGE,GRADE,GENDER) values ('hth0893','hth0893','0893',-1,-1,'M');
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "KITRI"."PK_MEMBER" ON "KITRI"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "KITRI"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KITRI"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
