--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_DETAIL
--------------------------------------------------------

  CREATE TABLE "KITRI"."MEMBER_DETAIL" 
   (	"EMAIL" VARCHAR2(35 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"ADDRESS_DETAIL" VARCHAR2(100 BYTE), 
	"JOINDATE" DATE, 
	"OUTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KITRI.MEMBER_DETAIL
SET DEFINE OFF;
Insert into KITRI.MEMBER_DETAIL (EMAIL,ADDRESS,ADDRESS_DETAIL,JOINDATE,OUTDATE) values ('hth0893',null,null,null,null);
--------------------------------------------------------
--  DDL for Index PK_MEMBER_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "KITRI"."PK_MEMBER_DETAIL" ON "KITRI"."MEMBER_DETAIL" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_DETAIL
--------------------------------------------------------

  ALTER TABLE "KITRI"."MEMBER_DETAIL" ADD CONSTRAINT "PK_MEMBER_DETAIL" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KITRI"."MEMBER_DETAIL" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_DETAIL
--------------------------------------------------------

  ALTER TABLE "KITRI"."MEMBER_DETAIL" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_DETAIL" FOREIGN KEY ("EMAIL")
	  REFERENCES "KITRI"."MEMBER" ("EMAIL") ENABLE;
