--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRIP_BASIC
--------------------------------------------------------

  CREATE TABLE "KITRI"."TRIP_BASIC" 
   (	"TRIP_SEQ" NUMBER, 
	"EMAIL" VARCHAR2(35 BYTE), 
	"TRIP_NUM" NUMBER(3,0), 
	"TRIP_TITLE" VARCHAR2(50 BYTE), 
	"TRIP_THEME" VARCHAR2(15 BYTE), 
	"TRIP_SEASON" VARCHAR2(4 BYTE), 
	"START_DATE" DATE DEFAULT sysdate, 
	"END_DATE" DATE DEFAULT sysdate, 
	"VIEWCOUNT" NUMBER, 
	"LIKECOUNT" NUMBER, 
	"LASTUPDATE" DATE, 
	"ISCOMPLETE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KITRI.TRIP_BASIC
SET DEFINE OFF;
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (82,'hth0893',4,'제주 2박 3일 여행','함께타요','봄',to_date('19/07/22','RR/MM/DD'),to_date('19/07/24','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (83,'hth0893',2,'1박 2일 부산여행','친구','겨울',to_date('19/07/24','RR/MM/DD'),to_date('19/07/25','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (85,'hth0893',4,'충북여행','함께타요','여름',to_date('19/07/23','RR/MM/DD'),to_date('19/07/23','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (88,'hth0893',2,'결혼 1주년 기념','커플','봄',to_date('19/07/24','RR/MM/DD'),to_date('19/07/26','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (90,'hth0893',6,'동해 경치속에서 행복여행','함께타요','겨울',to_date('19/07/23','RR/MM/DD'),to_date('19/07/23','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (91,'hth0893',2,'서울, 대전 여행','친구','봄',to_date('19/07/22','RR/MM/DD'),to_date('19/07/23','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (84,'hth0893',1,'4박5일 대전','나홀로','봄',to_date('19/07/22','RR/MM/DD'),to_date('19/07/26','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (86,'hth0893',1,'서울여행1','함께타요','가을',to_date('19/07/30','RR/MM/DD'),to_date('19/07/30','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (87,'hth0893',10,'동아리활동 현장체험','함께타요','여름',to_date('19/07/23','RR/MM/DD'),to_date('19/07/23','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (92,'hth0893',1,'4~6일 서울, 대전','나홀로','봄',to_date('19/07/22','RR/MM/DD'),to_date('19/07/26','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
Insert into KITRI.TRIP_BASIC (TRIP_SEQ,EMAIL,TRIP_NUM,TRIP_TITLE,TRIP_THEME,TRIP_SEASON,START_DATE,END_DATE,VIEWCOUNT,LIKECOUNT,LASTUPDATE,ISCOMPLETE) values (89,'hth0893',5,'가족여행','가족','봄',to_date('19/07/31','RR/MM/DD'),to_date('19/08/05','RR/MM/DD'),0,0,to_date('19/07/22','RR/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Index PK_TRIP_BASIC
--------------------------------------------------------

  CREATE UNIQUE INDEX "KITRI"."PK_TRIP_BASIC" ON "KITRI"."TRIP_BASIC" ("TRIP_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRIP_BASIC
--------------------------------------------------------

  ALTER TABLE "KITRI"."TRIP_BASIC" ADD CONSTRAINT "PK_TRIP_BASIC" PRIMARY KEY ("TRIP_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("TRIP_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("TRIP_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("TRIP_TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("TRIP_THEME" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("TRIP_SEASON" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("LASTUPDATE" NOT NULL ENABLE);
 
  ALTER TABLE "KITRI"."TRIP_BASIC" MODIFY ("ISCOMPLETE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRIP_BASIC
--------------------------------------------------------

  ALTER TABLE "KITRI"."TRIP_BASIC" ADD CONSTRAINT "FK_MEMBER_TO_TRIP_BASIC" FOREIGN KEY ("EMAIL")
	  REFERENCES "KITRI"."MEMBER" ("EMAIL") ENABLE;
